name: sniffeed_content_image_creator
description: Sniffeed Image Content Creator.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.0.1
  file_picker: ^4.5.1
  screenshot: ^1.2.3
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true
  fonts:
    - family: Score_Dream
      fonts:
        - asset: assets/fonts/scoredream/SCDream1.otf
          weight: 100 # Thin
        - asset: assets/fonts/scoredream/SCDream2.otf
          weight: 200 # Extra Light
        - asset: assets/fonts/scoredream/SCDream3.otf
          weight: 300 # Light
        - asset: assets/fonts/scoredream/SCDream4.otf
          weight: 400 # Regular
        - asset: assets/fonts/scoredream/SCDream5.otf
          weight: 500 # Medium
        - asset: assets/fonts/scoredream/SCDream6.otf
          weight: 600 # Bold
        - asset: assets/fonts/scoredream/SCDream7.otf
          weight: 700 # Extra Bold
        - asset: assets/fonts/scoredream/SCDream8.otf
          weight: 800 # Heavy
        - asset: assets/fonts/scoredream/SCDream9.otf
          weight: 900 # Black
  assets:
    - assets/images/